[package]
name = "silentsilo-mobile"
version = "0.1.0"
description = "SilentSilo for Android and iOS"
authors = ["SilentSilo"]
edition = "2024"
rust-version = "1.94"
license = "AGPL-3.0-or-later"

[lib]
name = "silentsilo_mobile_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
silentsilo-core = { workspace = true }
silentsilo-crypto = { workspace = true }
silentsilo-vault = { workspace = true }
silentsilo-vfs = { workspace = true }
silentsilo-store = { workspace = true }
silentsilo-sync = { workspace = true }
silentsilo-app = { workspace = true }
uuid = { version = "1", features = ["v4"] }
hex = "0.4"
tokio = { version = "1", features = ["time"] }
silentsilo-fido = { workspace = true, features = ["enclave"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
